/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chat.ui.gui;

import com.chat.ui.console.UI_Chat;
import com.chat.ui.console.UI_Register;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author wenfi
 */
public class UI_Login extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form Conexion
     */
    public UI_Login() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    public JLabel getURLregister() {
        return URLregister;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bg = new javax.swing.JPanel();
        User = new javax.swing.JTextField();
        UserSeparator = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        BtnEnter = new javax.swing.JPanel();
        TxtEntrar = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        Exitbtn = new javax.swing.JPanel();
        TxtExit = new javax.swing.JLabel();
        TxtSessionStart = new javax.swing.JLabel();
        TxtUser = new javax.swing.JLabel();
        BtnRegister = new javax.swing.JPanel();
        URLregister = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(153, 204, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setRequestFocusEnabled(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User.setBackground(new java.awt.Color(153, 204, 255));
        User.setForeground(new java.awt.Color(153, 153, 153));
        User.setText("Ingrese el usuario");
        User.setBorder(null);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserMousePressed(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        bg.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 420, 40));
        bg.add(UserSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 420, -1));

        Logo.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        Logo.setForeground(new java.awt.Color(102, 153, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO.png"))); // NOI18N
        Logo.setText("WHATSABLUE");
        bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        BtnEnter.setBackground(new java.awt.Color(7, 134, 184));

        TxtEntrar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        TxtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        TxtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtEntrar.setText("ENTRAR");
        TxtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnEnterLayout = new javax.swing.GroupLayout(BtnEnter);
        BtnEnter.setLayout(BtnEnterLayout);
        BtnEnterLayout.setHorizontalGroup(
            BtnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEnterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnEnterLayout.setVerticalGroup(
            BtnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEnterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(BtnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 40));

        header.setBackground(new java.awt.Color(153, 204, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(153, 204, 255));
        Exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitbtnMouseClicked(evt);
            }
        });

        TxtExit.setBackground(new java.awt.Color(255, 255, 255));
        TxtExit.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        TxtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtExit.setText("x");
        TxtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitbtnLayout = new javax.swing.GroupLayout(Exitbtn);
        Exitbtn.setLayout(ExitbtnLayout);
        ExitbtnLayout.setHorizontalGroup(
            ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitbtnLayout.setVerticalGroup(
            ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 450, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        TxtSessionStart.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TxtSessionStart.setText("INICIAR SESIÓN");
        bg.add(TxtSessionStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        TxtUser.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TxtUser.setText("USUARIO");
        bg.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        BtnRegister.setBackground(new java.awt.Color(153, 204, 255));

        URLregister.setBackground(new java.awt.Color(153, 204, 255));
        URLregister.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        URLregister.setText("¿Aún no tienes usuario?Registrate aquí!");
        URLregister.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        URLregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        URLregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                URLregisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BtnRegisterLayout = new javax.swing.GroupLayout(BtnRegister);
        BtnRegister.setLayout(BtnRegisterLayout);
        BtnRegisterLayout.setHorizontalGroup(
            BtnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(URLregister, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BtnRegisterLayout.setVerticalGroup(
            BtnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnRegisterLayout.createSequentialGroup()
                .addComponent(URLregister, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void TxtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TxtExitMouseClicked

    private void TxtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseEntered
        Exitbtn.setBackground(Color.red);
        TxtExit.setForeground(Color.white);
    }//GEN-LAST:event_TxtExitMouseEntered

    private void TxtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseExited
    Exitbtn.setBackground(new Color(153, 204, 255));
    TxtExit.setForeground(Color.black);
    }//GEN-LAST:event_TxtExitMouseExited

    private void ExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseClicked
    }//GEN-LAST:event_ExitbtnMouseClicked

    private void TxtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseEntered
        BtnEnter.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_TxtEntrarMouseEntered

    private void TxtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseExited
        BtnEnter.setBackground(new Color(7,134,184));
    }//GEN-LAST:event_TxtEntrarMouseExited

    private void UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMousePressed
        if(User.getText().equals("Ingrese el usuario")){
            User.setText("");
            User.setForeground(Color.black);
        }

    }//GEN-LAST:event_UserMousePressed

    private void TxtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseClicked
        // Obtener el usuario ingresado
        String usuario = User.getText().trim();
        
        // Cerrar ventana actual
        this.dispose();
        
        // Abrir nueva ventana UI_AddContact
        SwingUtilities.invokeLater(() -> {
            UI_Chat connectionWindow = new UI_Chat();
            connectionWindow.setVisible(true);
        });    
    }//GEN-LAST:event_TxtEntrarMouseClicked

    private void URLregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_URLregisterMouseClicked
    // Cerrar ventana actual
    this.dispose();
    
    // Abrir ventana de registro
    SwingUtilities.invokeLater(() -> {
        UI_Register registerWindow = new UI_Register();
        registerWindow.setVisible(true);
    });
    }//GEN-LAST:event_URLregisterMouseClicked
    private void URLregisterMouseEntered(java.awt.event.MouseEvent evt) {
        URLregister.setForeground(new Color(102, 153, 255));
    }
    
    private void URLregisterMouseExited(java.awt.event.MouseEvent evt) {
        URLregister.setForeground(Color.black);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnEnter;
    private javax.swing.JPanel BtnRegister;
    private javax.swing.JPanel Exitbtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TxtEntrar;
    private javax.swing.JLabel TxtExit;
    private javax.swing.JLabel TxtSessionStart;
    private javax.swing.JLabel TxtUser;
    private javax.swing.JLabel URLregister;
    private javax.swing.JTextField User;
    private javax.swing.JSeparator UserSeparator;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel header;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
