/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chat.ui.console;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author wenfi
 */
public class Login extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form Conexion
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null); 

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bg = new javax.swing.JPanel();
        TxtAppChat = new javax.swing.JLabel();
        Imagen_Derecha = new javax.swing.JLabel();
        TxtRealizarCon = new javax.swing.JLabel();
        TxtIP = new javax.swing.JLabel();
        IP = new javax.swing.JTextField();
        IpSeparator = new javax.swing.JSeparator();
        TxtPuerto = new javax.swing.JLabel();
        Puerto = new javax.swing.JTextField();
        PuertoSeparator = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JPanel();
        TxtEntrar = new javax.swing.JLabel();
        Fondo_Derecha = new javax.swing.JPanel();
        Avatar = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        Exitbtn = new javax.swing.JPanel();
        TxtExit = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(153, 204, 255));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setRequestFocusEnabled(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtAppChat.setBackground(new java.awt.Color(255, 255, 255));
        TxtAppChat.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        TxtAppChat.setForeground(new java.awt.Color(153, 204, 255));
        TxtAppChat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtAppChat.setText("APP CHAT");
        bg.add(TxtAppChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 310, 40));

        Imagen_Derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mobile-phone-6721915_1280.png"))); // NOI18N
        bg.add(Imagen_Derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 310, 380));

        TxtRealizarCon.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        TxtRealizarCon.setText("REALIZAR CONEXIÓN");
        bg.add(TxtRealizarCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        TxtIP.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TxtIP.setText("IP");
        bg.add(TxtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, -1));

        IP.setBackground(new java.awt.Color(153, 204, 255));
        IP.setForeground(new java.awt.Color(153, 153, 153));
        IP.setText("Ingrese la IP");
        IP.setBorder(null);
        IP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IPMousePressed(evt);
            }
        });
        IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPActionPerformed(evt);
            }
        });
        bg.add(IP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 420, 40));
        bg.add(IpSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 420, -1));

        TxtPuerto.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TxtPuerto.setText("PUERTO");
        bg.add(TxtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, -1));

        Puerto.setBackground(new java.awt.Color(153, 204, 255));
        Puerto.setForeground(new java.awt.Color(153, 153, 153));
        Puerto.setText("Ingrese el puerto");
        Puerto.setBorder(null);
        Puerto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PuertoMousePressed(evt);
            }
        });
        Puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuertoActionPerformed(evt);
            }
        });
        bg.add(Puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 420, 40));
        bg.add(PuertoSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 420, -1));

        Logo.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        Logo.setForeground(new java.awt.Color(102, 153, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO.png"))); // NOI18N
        Logo.setText("WHATSABLUE");
        bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        BtnEntrar.setBackground(new java.awt.Color(7, 134, 184));

        TxtEntrar.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        TxtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        TxtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtEntrar.setText("ENTRAR");
        TxtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnEntrarLayout = new javax.swing.GroupLayout(BtnEntrar);
        BtnEntrar.setLayout(BtnEntrarLayout);
        BtnEntrarLayout.setHorizontalGroup(
            BtnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnEntrarLayout.setVerticalGroup(
            BtnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 40));

        Fondo_Derecha.setBackground(new java.awt.Color(7, 134, 184));

        Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N

        javax.swing.GroupLayout Fondo_DerechaLayout = new javax.swing.GroupLayout(Fondo_Derecha);
        Fondo_Derecha.setLayout(Fondo_DerechaLayout);
        Fondo_DerechaLayout.setHorizontalGroup(
            Fondo_DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_DerechaLayout.createSequentialGroup()
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Fondo_DerechaLayout.setVerticalGroup(
            Fondo_DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_DerechaLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(Avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(Fondo_Derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 310, 170));

        header.setBackground(new java.awt.Color(153, 204, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(153, 204, 255));
        Exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitbtnMouseClicked(evt);
            }
        });

        TxtExit.setBackground(new java.awt.Color(255, 255, 255));
        TxtExit.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        TxtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtExit.setText("x");
        TxtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitbtnLayout = new javax.swing.GroupLayout(Exitbtn);
        Exitbtn.setLayout(ExitbtnLayout);
        ExitbtnLayout.setHorizontalGroup(
            ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitbtnLayout.setVerticalGroup(
            ExitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPActionPerformed

    private void PuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuertoActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void TxtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TxtExitMouseClicked

    private void TxtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseEntered
        Exitbtn.setBackground(Color.red);
        TxtExit.setForeground(Color.white);
    }//GEN-LAST:event_TxtExitMouseEntered

    private void TxtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtExitMouseExited
    Exitbtn.setBackground(new Color(153, 204, 255));
    TxtExit.setForeground(Color.black);
    }//GEN-LAST:event_TxtExitMouseExited

    private void ExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseClicked
    }//GEN-LAST:event_ExitbtnMouseClicked

    private void TxtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseEntered
        BtnEntrar.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_TxtEntrarMouseEntered

    private void TxtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseExited
        BtnEntrar.setBackground(new Color(7,134,184));
    }//GEN-LAST:event_TxtEntrarMouseExited

    private void IPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IPMousePressed
        if(IP.getText().equals("Ingrese la IP")){
            IP.setText("");
            IP.setForeground(Color.black);
        }
        if(Puerto.getText().equals("")){
            Puerto.setText("Ingrese el puerto");
            Puerto.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_IPMousePressed

    private void PuertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PuertoMousePressed
        if(Puerto.getText().equals("Ingrese el puerto")){
            Puerto.setText("");
            Puerto.setForeground(Color.black);
        }
        if(IP.getText().equals("")){
            IP.setText("Ingrese la IP");
            IP.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PuertoMousePressed

    private void TxtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JPanel BtnEntrar;
    private javax.swing.JPanel Exitbtn;
    private javax.swing.JPanel Fondo_Derecha;
    private javax.swing.JTextField IP;
    private javax.swing.JLabel Imagen_Derecha;
    private javax.swing.JSeparator IpSeparator;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Puerto;
    private javax.swing.JSeparator PuertoSeparator;
    private javax.swing.JLabel TxtAppChat;
    private javax.swing.JLabel TxtEntrar;
    private javax.swing.JLabel TxtExit;
    private javax.swing.JLabel TxtIP;
    private javax.swing.JLabel TxtPuerto;
    private javax.swing.JLabel TxtRealizarCon;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel header;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
